version: "3.7"
services:
  db:
    container_name: studentsdb
    restart: always
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - /var/lib/docker/volumes/students:/var/lib/postgresql/data
    ports:
      - "5435:5432"
