"""empty message

Revision ID: 76be054651f3
Revises: d2258d2a88bd
Create Date: 2022-04-25 13:26:30.862801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76be054651f3"
down_revision = "d2258d2a88bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("student", sa.Column("created_date", sa.DateTime(), nullable=True))
    op.drop_column("student", "favorite_subject")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "student",
        sa.Column("favorite_subject", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("student", "created_date")
    # ### end Alembic commands ###
