"""empty message

Revision ID: c883f3f16485
Revises: 76be054651f3
Create Date: 2022-04-25 13:28:49.041505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c883f3f16485'
down_revision = '76be054651f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('subject', sa.Column('name', sa.String(), nullable=True))
    op.drop_constraint('subject_email_key', 'subject', type_='unique')
    op.create_unique_constraint(None, 'subject', ['name'])
    op.drop_column('subject', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subject', type_='unique')
    op.create_unique_constraint('subject_email_key', 'subject', ['email'])
    op.drop_column('subject', 'name')
    op.alter_column('student', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
