"""empty message

Revision ID: d2258d2a88bd
Revises: 
Create Date: 2022-04-21 16:56:10.357952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2258d2a88bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('favorite_subject', sa.String(), nullable=True))
    op.add_column('student', sa.Column('total_spent_books', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'total_spent_books')
    op.drop_column('student', 'favorite_subject')
    # ### end Alembic commands ###
